package com.jaideep.expensetracker.common.constant

enum class TransactionMethod {
    GET_TRANSACTIONS_FOR_ACCOUNT,
    GET_DEBIT_TRANSACTIONS_FOR_ACCOUNT,
    GET_CREDIT_TRANSACTIONS_FOR_ACCOUNT,
    GET_CREDIT_TRANSACTIONS_BETWEEN_DATES_FOR_ACCOUNT,
    GET_DEBIT_TRANSACTIONS_BETWEEN_DATES_FOR_ACCOUNT,
    GET_TRANSACTIONS_BETWEEN_DATES_FOR_ACCOUNT,
    GET_ALL_TRANSACTIONS,
    GET_DEBIT_TRANSACTIONS,
    GET_CREDIT_TRANSACTIONS,
    GET_CREDIT_TRANSACTIONS_BETWEEN_DATES,
    GET_DEBIT_TRANSACTIONS_BETWEEN_DATES,
    GET_TRANSACTIONS_BETWEEN_DATES
}